
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/octet-stream
  port: 8082
# mongodb specific properties

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gonogo_analytics_config
      database: gonogo_analytics_config
      baseuri: mongodb://localhost:27017
  profiles: dev

kafka:
  bootstrap-servers: localhost:9092
  topic: cyod-data
  group-id: cyod
  port: 9092
zookeeper:
  ip: localhost
  port: 2181

